accounts/urls.py
from os import name
from django.urls import path
from . import views
import accounts

app_name = 'accounts'
urlpatterns = [
    path('',views.home, name="home"),
    path('user/',views.userPage, name="user"),
    path('user_settings/',views.accountSettings,name='user_settings'),


    path('register/',views.register, name="register"),
    path('login/',views.loginPage, name="login"),
    path('logout/',views.logoutUser, name="logout"),

    path('products/',views.products,name="products"),
    path('customers/<str:pk>/',views.customers, name="customers"),

    path('create_order/<str:pk>',views.createOrder,name="create_order"),
    path('update_order/<str:pk>/',views.updateOrder,name="update_order"),
    path('delete_order/<str:pk>/',views.deleteOrder,name="delete_order"),
]

cma/urls.py
import accounts
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from os import name, truncate
from django.db import models
from django.db.models.deletion import SET_NULL
from django.contrib.auth.models import User
from django.db.models.fields import NullBooleanField

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True,on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200,blank=True, null=True)
    email = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        if self.name == None:
            return "ERROR-Customer name is NULL"
        return self.name

    class Meta:
        verbose_name_plural = 'Customers'

class Tag(models.Model):
    name = models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Tags'

class Product(models.Model):
    CATEGORY = (
        ('Indoor', 'Indoor'),
        ('Out door','Out door'),
        )
    name = models.CharField(max_length=200, null=True)
    price = models.CharField(max_length=200,null=True)
    category = models.CharField(max_length=200,null=True,choices=CATEGORY)
    description = models.CharField(max_length=200,null=True, blank=True)
    date_created= models.DateTimeField(auto_now_add=True,null=True)
    tags = models.ManyToManyField(Tag)
    

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Products'
    
class Order(models.Model):
    STATUS = (
        ('Pending','Pending'),
        ('Out for delivery','Out for delivery'),
        ('Delivered','Delivered'),
    )
    customer = models.ForeignKey(Customer, null=True, on_delete=SET_NULL)
    product = models.ForeignKey(Product, null=True,on_delete=SET_NULL) 
    date_created= models.DateTimeField(auto_now_add=True,null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name_plural = 'Orders'

accounts/forms.py
from django.db.models import fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User
from django import forms


from .models import *


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

class CreateUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']

accounts/views.py
from django.db.models.fields import EmailField
from accounts.decorators import unauthenticated_user
from django.shortcuts import render,redirect
from django.forms import inlineformset_factory

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

from django.contrib.auth import authenticate,login, logout
from .models import *
from .forms import OrderForm,CreateUserForm,CustomerForm
from .filters import OrderFilter

from .decorators import admin_only, unauthenticated_user, allowed_users
# Create your views here.

@unauthenticated_user
def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            username = form.cleaned_data.get('username')
            # email = form.cleaned_data.get('email')

            # group = Group.objects.get(name='customer')
            # user.groups.add(group)
            # Customer.objects.create(
            #     user=user,
            #     name = user.username,
            #     email = email,
            # )

            messages.success(request,'User account created for ' + username + ', login now.' )
            return redirect('accounts:login')
        
    context = {
        'form':form
    }

    return render(request,'accounts/register.html',context)


@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username=username,password=password)

        if user is not None:
            login(request, user)
            return redirect('accounts:home')
        else:
            messages.error(request, 'Username Or Password is incorrect!!')

    
    context = {
        }
    return render(request,'accounts/login.html',context)

def logoutUser(request):
    logout(request)
    return redirect('accounts:login')

# home dashboard page
@login_required(login_url='accounts:login')
@admin_only
def home(request):
    customer = Customer.objects.all()

    orders = Order.objects.all()

    total_orders = orders.count()
    delivered = orders.filter(status='Delivered').count()
    pending  = orders.filter(status='Pending').count()
    out_for_delivery = orders.filter(status='Out for delivery').count()
    context = {
        'customer': customer,
        'orders': orders,
        'total_orders': total_orders,
        'delivered':delivered,
        'pending':pending,
        'out_for_delivery':out_for_delivery
    }

    return render(request,'accounts/dashboard.html',context)

# Customer user page
@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['customer'])
def userPage(request):
    orders = request.user.customer.order_set.all()

    total_orders = orders.count()
    delivered = orders.filter(status='Delivered').count()
    pending  = orders.filter(status='Pending').count()
    out_for_delivery = orders.filter(status='Out for delivery').count()


    context = {
        'orders':orders,
        'total_orders': total_orders,
        'delivered':delivered,
        'pending':pending,
        'out_for_delivery':out_for_delivery,
    }
    return render (request,'accounts/user_page.html',context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['customer'])
def accountSettings(request):
    customer = request.user.customer

    form = CustomerForm(instance=customer)
    if request.method == 'POST':
        form = CustomerForm(request.POST,request.FILES, instance=customer)


        if form.is_valid():
            form.save()

            userUpdateField = {
                'username':customer.name,
                'email':customer.email
            }

            User.objects.filter(pk=request.user.id).update(username=userUpdateField['username'],email=userUpdateField['email'])

    context={
        'form':form
    }

    return render(request,'accounts/user_settings.html',context)







@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def products(request):
    products = Product.objects.all()

    return render(request,'accounts/products.html',{
        'products':products
    })


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customers(request,pk):
    customer = Customer.objects.get(id=pk)

    orders = customer.order_set.all()
    total_orders = orders.count()

    myFilter = OrderFilter(request.GET, queryset=orders)
    orders = myFilter.qs

    context = {
        'customer':customer,
        'orders':orders,
        'total_orders':total_orders,
        'myFilter':myFilter,
    }

    return render(request,'accounts/customers.html',context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def createOrder(request,pk):
    OrderFormSet = inlineformset_factory(Customer,Order,fields=('product','status'),extra=5)
    customer = Customer.objects.get(id=pk)

    formset = OrderFormSet(queryset=Order.objects.none(),instance=customer)
    if request.method =='POST':
        formset = OrderFormSet(request.POST,instance=customer)
        
        if formset.is_valid():
            formset.save()
            return redirect('/')


    context = {
        'form':formset,
        'customer':customer
    }

    return render(request,'accounts/order_form.html',context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def updateOrder(request,pk):
    customer = Customer.objects.get(id=pk)
    order = Order.objects.get(id=pk)
    form = OrderForm(instance=order)

    if request.method =='POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'form':form,
        'customer':customer
    }

    return render(request,'accounts/order_form.html',context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def deleteOrder(request,pk):
    order = Order.objects.get(id=pk)

    if request.method == 'POST':
        order.delete()
        return redirect('/')

    context = {
        'item':order
    }

    return render(request,'accounts/delete.html',context)

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>CMA</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
</head>
<body>
    {% include 'accounts/navbar.html' %}
    <div class="container-fluid">
        
        {% block content %}
        
        {% endblock %}

    </div>

<footer class="footer bottom text-center text-white py-3 bg-dark">
    <div class="container">
        <span class="text-muted">Customer Management System</span>
    </div>
</footer>




    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" 
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" 
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/customers.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}
{% block content %}
<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Customer: {{customer.name}} </h5>
            <hr>
            <a class="btn btn-outline-info btn-sm btn-block mt-1" href="#">Update Customer</a>

            <a href="{% url 'accounts:create_order'  customer.id %}" class="btn btn-outline-success btn-sm btn-block mt-3">Place new order</a>
        </div>

    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Contact Information:</h5>
            <hr>
            <p>Email: {{ customer.email }}</p>
            <p>Phone: {{ customer.phone }}</p>
            
        </div>

    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Total Orders:</h5>
            <hr>
            <h1 style="text-align:center;padding:10px">{{ total_orders }}</h1>
            
        </div>

    </div>
</div>

<br>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="GET">
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label class="label" >Products</label>
                            {% render_field myFilter.form.product class="form-select sm" %}
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="form-group">
                            <label class="label" >Status</label>
                            {% render_field myFilter.form.status class="form-select sm" %}
                        </div>
                    </div>

                    <div class="col-md-2 mt-4">
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                    </div>
                </form>
        </div>

    </div>
    
</div>

<br>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <div class="table-responsive">
                <table class="table table-sm">
                    <tr>
                        <th>Products</th>
                        <th>Category</th>
                        <th>Date Ordered</th>
                        <th>Status</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.product }}</td>
                            <td>{{ order.product.category }}</td>
                            <td>{{ order.date_created }}</td>
                            <td>{{ order.status }}</td>
                            <td> <a href="{% url 'accounts:update_order' order.id  %}" class='btn btn-success btn-sm' >Update</a> </td>
                            <td> <a href="{% url 'accounts:delete_order' order.id  %}" class='btn btn-danger btn-sm' >Delete</a> </td>
                        </tr>

                    {% endfor %}
                </table>
            </div>
        </div>

    </div>
    
</div>

{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}

    {% include 'accounts/status.html' %}
    <br>
        <div class="row">
            <!-- customers column -->
            <div class="col-md-5">
                <h5>CUSTOMERS:</h5>
                <hr>
                <div class="card">
                    <div class="card-body">
                        <a type="button" class="btn btn-primary d-grid gap-2">Create Customers</a>
                        <table class="table table-sm">
                            <tr>
                                <th>Customers</th>
                                <th>Phone</th>
                            </tr>
                            {% for customer in customer %}
                                <tr>
                                    <td><a style="text-decoration: none; color: black;" 
                                        href="{% url 'accounts:customers'  customer.id %}">{{ customer.name }}</a> </td>
                                    <td> {{ customer.phone }} </td>    
                                </tr>
                                
                            {% endfor %}
                        </table>
                        
                    </div>

                </div>
            </div>

            <!-- Order details column  -->
            <div class="col-md-7">
                <h5>LAST 5 ORDERS</h5>
                <hr>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm">
                                <tr>
                                    <th>Products</th>
                                    <th>Date Ordered</th>
                                    <th>Status</th>
                                    <th>Update</th>
                                    <th>Remove</th>
                                </tr>
                                {% for order in orders|slice:":5" %}

                                <tr>
                                    <td> {{ order.product }} </td>
                                    <td> {{ order.date_created }} </td>
                                    <td> {{ order.status }} </td>
                                    <td> <a href="{% url 'accounts:update_order' order.id  %}" class='btn btn-success btn-sm' >Update</a> </td>
                                    <td> <a href="{% url 'accounts:delete_order' order.id  %}" class='btn btn-danger btn-sm' >Delete</a> </td>
                                </tr>    
                                {% endfor %}
                            </table>
                        </div>
                    </div>

                </div>
            </div>

        </div>

{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'accounts/base.html' %}

{% block content %}
<br>
    <div class="row">
        <div class="col-md-6">
            <div class="card card-body">
                <p>Are you sure want to delete {{item}}?</p>
                <form action="" method="POST">
                    {% csrf_token %}
                        <input type="submit" value="Yeet" class='btn btn-danger btn-sm'>
                        <a href="{% url 'accounts:home' %}" class='btn btn-warning btn-sm'>Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/signup_login_base.html' %}

{% block content %}
    <div class="col-sm-5" >
        <div class="card-body" id="register-right-side-content">
            <br>
            <h3 class="card-title mb-4">Login</h3>
            <hr style="background-color: #000000;width: 100%;">
            <div class="form-group">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Username</span>
                        </div>
                        <input type="text" class="form-control" name="username" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Password</span>
                        </div>
                        <input type="password" class="form-control" name="password" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                    </div>
                    <button type="submit"  class="btn btn-primary">Login</button>
                </form>
            </div>
            <p>Don't have an account?
                <a href="{% url 'accounts:register' %}">Sign Up</a>
            </p>
        </div>
    </div>

{% endblock %}


































<!-- {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" 
            integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    
    <title>Login</title>
</head>
<body>
    {% include 'accounts/messages.html' %}
    <div class="d-flex align-items-center min-vh-100 py-3 py-md-0">
        <div class="container">
            <div class="card login-card">
                <div class="row no-gutters">
                    <div class="col-sm-5" id="register-left-side">
                        <div class="card-body">
                            <h1 class="card-title text-center text-white mt-5 mb-5">Content Management System</h1>
                            <hr>
                            <p class="card-header text-center text-white mt-5">Register or Login here to access CMS Application</p>
                        </div>
                    </div>

                    <div class="col-sm-5" >
                        <div class="card-body" id="register-right-side-content">
                            <br>
                            <h3 class="card-title mb-4">Login</h3>
                            <hr style="background-color: #000000;width: 100%;">
                            <div class="form-group">
                                <form method="POST" action="">
                                    {% csrf_token %}
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                          <span class="input-group-text" id="inputGroup-sizing-default">Username</span>
                                        </div>
                                        <input type="text" class="form-control" name="username" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                                    </div>

                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                          <span class="input-group-text" id="inputGroup-sizing-default">Password</span>
                                        </div>
                                        <input type="password" class="form-control" name="password" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                                    </div>

                                    <button type="submit"  class="btn btn-primary">Login</button>
                                </form>
                            </div>
                            <p>Don't have an account?
                                <a href="{% url 'accounts:register' %}">Sign Up</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html> -->

accounts/templates/accounts/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    {{ message }}
  </div>
{% endfor %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

accounts/templates/accounts/navbar.html
<style>
  .user-login-feed {
    font-size: 15px;
    color: #FFF;
    padding-right: 5px;
    margin-right: 20px;
    text-decoration: none;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" id="logo">CMS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'accounts:home' %}">Dashboard</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'accounts:products' %}">Products</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'accounts:user' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'accounts:user_settings' %}">Settings</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    {% if request.user.is_staff %}
      <span class="user-login-feed">Hello, {{request.user.username}}
    {% else %}
    <span class="user-login-feed">Hello, {{request.user.customer.name}}
    {% endif %}
      <span ><a class="user-login-feed" href="{% url 'accounts:logout' %}">Logout</a></span>
    </span>
  </nav>

accounts/templates/accounts/order_form.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content %}
<br>
    <div class="row">
        <div class="col-md-6">
            <div class="card card-body">
                <h5>Customer:{{customer.name}} </h5>
                <br>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{formset.management_form}}
                    {% for form in form %}
                        {{ form }}
                        <hr>
                    {% endfor %}
                    <input type="submit" name="Submit" class='btn btn-success btn-sm'>
                    <a href="{% url 'accounts:customers' customer.id %}" class='btn btn-warning btn-sm'>Cancel</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/products.html
{% extends 'accounts/base.html' %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Products</h5>
        </div>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Products</th>
                    <th>Category</th>
                    <th>Price</th>
                </tr>
                {% for items in products %}
                    <tr>
                        <td>{{ items.name }}</td>
                        <td>{{ items.category }}</td>
                        <td>{{ items.price }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/user_page.html
{% extends 'accounts/base.html' %}

{% block content %}
<br>
<h3>User Profile</h3>
<hr>
{% include 'accounts/status.html' %}

<div class="row">
    <div class="col">
        <div class="card card-body">
            <div class="table-responsive">
                <table class="table table-sm">
                    <tr>
                        <th>Products</th>
                        <th>Category</th>
                        <th>Date Ordered</th>
                        <th>Status</th>
                    </tr>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.product }}</td>
                            <td>{{ order.product.category }}</td>
                            <td>{{ order.date_created }}</td>
                            <td>{{ order.status }}</td>
                        </tr>

                    {% endfor %}
                </table>
            </div>
        </div>

    </div>
    
</div>
   
{% endblock %}

accounts/templates/accounts/user_settings.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<style>
    img{
        max-width: 200px;
        max-height: 200px;
        margin: 0 auto; 
        border-radius: 50%;
    }

</style>
<br>
<div class="row">
    <div class="col-md-3">
        <div class="card card-body">
            <div class="d-grid gap-2 d-md-block">
                <a class="btn btn-outline-dark" href="{% url 'accounts:user' %}">&#8592; Back</a>
            </div>
            <hr style="background-color: #000000; margin:auto; margin-top: 15px;">
            <br>
            <h5 class="card-title text-center">{{request.user.customer.name}}</h5>
            <br>
            {% if request.user.customer.profile_pic %}
                <img src="{{ request.user.customer.profile_pic.url }}" class="img-fluid" alt="100x100">
            
            {% else %}
                <img src = "{% static 'images/default-user-image.png' %}" class="img-fluid">
            {% endif %}
        </div>
    </div>

    <div class="col-md-5">
        <div class="card card-body">
            <h5 class="card-title">Account Details</h5>
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="mb-1">
                    <label for="exampleFormControlInput1" class="form-label">Name</label>
                    {% render_field form.name type="text" class="form-control" id="exampleFormControlInput1" placeholder="Name" %}
                </div>

                <div class="mb-1">
                    <label for="exampleFormControlInput1" class="form-label">Email</label>
                    {% render_field form.email type="email" class="form-control" id="exampleFormControlInput1" placeholder="Email" %}
                </div>

                <div class="mb-1">
                    <label for="exampleFormControlInput1" class="form-label">Phone</label>
                    {% render_field form.phone type="text" class="form-control" id="exampleFormControlInput1" placeholder="Phone" %}
                </div>

                <div class="mb-3">
                    <label for="formFile" class="form-label">Profile Pic</label>
                    {% render_field form.profile_pic type="file" class="form-control" id="formFile" placeholder="Choose file" label="" %}
                    
                </div>
                <button type="submit"  class="btn btn-primary">Save</button>
            </form>
        
        
        </div>
    </div>
</div>

<br>
{% endblock %}